<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Client Setup</name>
   <tag></tag>
   <elementGuidId>87069f22-e690-4241-8180-cc429a8158ce</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container-fluid form-horizontal page-content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pageContent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

        
            
                
                    Client Setup
                
            

            
                
            
                


                    Send Email

                    Close



                    ← Back


                    Next →





                    Save


                
            
        
            
        

        

        


    



        


            
                Please fill in every part of the page that applies to you
            
            
        






        


        

        

            
                
                    Please create at-least one pay schedule.
                
            

            
                
                    Pay Schedules (Select multiple if you have more than one pay schedule)
                
            

            


            
                
                    
                        

                        

                        
                            First payroll period end date
                        

                        
                            First pay date
                        
                    
                
            
            
                

                    

                        
                            
                                 
                            

                            
                                Weekly
                            

                        

                        
                            

                        

                        
                            
                        

                    
                
            


            
                
                    


                        

                            
                                 
                            

                            
                                Bi-Weekly
                            

                        

                        
                            

                        

                        

                            


                        

                    
                
            


            
                
                    

                        

                            
                                 
                            

                            
                                Semi-Monthly
                            

                        

                        

                            

                        

                        
                            


                        

                    
                
            


            
                
                    
                        

                            
                                 
                            

                            
                                Monthly
                            

                        

                        
                            


                        

                        

                            

                        
                    
                
            


            
                
                    
                        

                            
                                 
                            

                            
                                Quarterly
                            
                        

                        

                            

                        

                        
                            


                        

                    
                
            


            
            
            
            
        


        

        

            

                
                    Federal tax filing information
                


                

                

                    
                        Federal EIN Number:*
                    

                    
                             
                    
                

                
                    
                        Employer Type:
                    
                

                


                    
                         Quarterly (Form 941) Annual (Form 944) Agricultural (Form 943) Household employer (Schedule H)
                    

                



                
                    
                        Tax Payment Frequency:
                    

                    
                        Semi-WeeklyMonthlyWith Form
                    
                
            
            



            



            

                
                    State Tax Filing Information (New York)
                
                
                

                    
                        Employer State ID:
                    

                    
                             
                    
                

                

                    
                        Frequency:
                    

                    
                        3 Days 5 Days Quarterly

                    
                


                

                    
                         Unemployment Account:
                    

                    
                             
                    
                
                

                    
                        Unemployment %:
                    

                    
                        
                    
                


            

            
            
            
        

        



        

        

            
                
                
                    
                        
                            Select Applicable Pay Type
                        
                    
                    



                        

                            
                                Paytypes:
                            

                            
                                Action:
                            

                        

                        

                            
                                Regular
                            

                            
                                 
                            

                        

                        

                            
                                Vacation
                            

                            
                                 
                            

                        

                        

                            
                                Holiday
                            

                            
                                 
                            

                        

                        

                            
                                Reimbursement
                            

                            
                                 
                            

                        

                        

                            
                                Overtime
                            

                            
                                 
                            

                        

                        

                            
                                Bonus
                            

                            
                                 
                            

                        

                        

                            
                                Tips
                            

                            
                                 
                            

                        
                        

                            
                                Commission
                            

                            
                                 
                            

                        
                    
                
            

            


            

            
                
                
                    
                        
                            Select Applicable Deductions
                        
                    
                    
                        

                            
                            

                            
                                Criterion
                            

                            
                                Amt/Pct
                            

                        

                        
                            

                                
                                     
                                

                                
                                    401K
                                

                            

                            
                                --Select--Fixed Amt ($)       % of Gross          % of Net            % of Gross-Tax      Amt ($) per Hr      % of Compensation   Amt ($) per Month   Direct Entry        % Gross w/Cash Tips % Gross w/Cash Tips 
                            

                            
                                
                            

                        

                        
                            

                                
                                     
                                

                                
                                    Child Support
                                

                            

                            
                                
                            

                            
                                
                            
                        

                        
                            

                                
                                     
                                

                                
                                    Union Dues
                                

                            

                            
                                --Select--Fixed Amt ($)       % of Gross          % of Net            % of Gross-Tax      Amt ($) per Hr      % of Compensation   Amt ($) per Month   Direct Entry        % Gross w/Cash Tips % Gross w/Cash Tips 
                            

                            
                                
                            
                        

                        
                            

                                
                                     
                                

                                
                                    Health Savings Account
                                

                            

                            
                                --Select--Fixed Amt ($)       % of Gross          % of Net            % of Gross-Tax      Amt ($) per Hr      % of Compensation   Amt ($) per Month   Direct Entry        % Gross w/Cash Tips % Gross w/Cash Tips 
                            

                            
                                
                            

                        


                        
                            
                                
                                     
                                
                                
                                    Medical Insurance
                                
                            
                            
                                --Select--Fixed Amt ($)       % of Gross          % of Net            % of Gross-Tax      Amt ($) per Hr      % of Compensation   Amt ($) per Month   Direct Entry        % Gross w/Cash Tips % Gross w/Cash Tips 
                            

                            
                                
                            
                        

                        
                            
                                
                                     
                                
                                
                                    Dental Insurance
                                
                            
                            
                                --Select--Fixed Amt ($)       % of Gross          % of Net            % of Gross-Tax      Amt ($) per Hr      % of Compensation   Amt ($) per Month   Direct Entry        % Gross w/Cash Tips % Gross w/Cash Tips 
                            

                            
                                
                            
                        

                        
                            

                                
                                     
                                

                                
                                    Vision Insurance
                                

                            

                            
                                --Select--Fixed Amt ($)       % of Gross          % of Net            % of Gross-Tax      Amt ($) per Hr      % of Compensation   Amt ($) per Month   Direct Entry        % Gross w/Cash Tips % Gross w/Cash Tips 
                            

                            

                                
                            
                        


                    
                
            
        

        

        

        
            
                
                    Departments
                
            

            
                
                    

                        
                            
                                
                                    Enter Departments if you allocate employee earnings by departments
                                
                            
                        

                        

                            
                                
                                    Department Name
                                
                            
                        

                        
                            
                                
                                    
                                
                            
                            
                                
                                    
                                
                            
                            
                                

                                    
                                
                            
                        

                        
                            
                                
                                    
                                
                            
                            
                                
                                    
                                
                            
                            
                                

                                    

                                
                            
                        

                        
                            
                                
                                    
                                
                            
                            
                                
                                    
                                
                            
                            
                                

                                    

                                
                            
                        

                    
                
            
            
        
    

    

    



    

        

            
                
                    PTO Policy
                
            


            
                
                    How do employees accrue PTO
                
            

            
                
                    
                         per Pay Period per Month per Year per Hour Worked per Regular Hour Worked None
                    

                
            

            
            
                
                    How would you like to rollover PTO
                
            

            
                
                    
                         By Calendar Year By Hire Date Anniversary By Fiscal Year
                    


                    
                         
                    

                
            
        
        

        



        

        
        



            
                
                    Business Information
                

            
            
                

                    EFT Information:


                    
                         
                    
                

            
            
                
                    Business Website:

                    
                        
                    


                    

                    
                
            

            

                


                    Type:*

                    
                        &lt;Select>CorporationLimited Liability CompanyS CorporationSole ProprietorshipClosely HeldPartnershipPublicly HeldNon Profit    


                    

                



                


                    Years in Business: *

                    
                             


                    

                



            

            
                


                    Products/Services:*

                    
                            
                    

                

                


                    Net DD per Payday:

                    
                        
                    

                

            


            


            



            


            
                
                    Principal
                
            

            

                

                    
                        Name:*
                    
                    
                            
                    

                

                
                   
                        Full Home Address:
                   
                    
                         
                    
                
            

            

                

                    
                        Home Phone:
                    
                    
                        
                    

                


                

                    
                        Title:*
                    
                    
                            
                    

                

                

                    
                        SSN:*
                    
                    
                            
                    

                



                
                  
                        Equity(%):
                    
                    
                        
                    
                



            

            

            

            


        


        

            
                
                    Thank you for providing the setup information.
                
            

        




        


        


        
            
                
            
        

        
            
                
            
            
            
        

        
            
                
            
        

        
            
                
            
            
                
            
        

        
            
                
                    
                

                

                    

                

            
            
                
            

        

        
            
                
                    
                
            
        


        

        
            

                

                    
                        
                            
                        
                    

                    

                    

                
            
        

        
            

                

                    
                        
                            
                        
                    

                    

                    

                
            
        

        
            

                

                    
                        
                            
                        
                    

                    

                    

                
            
        


        
            

                

                    
                        
                            
                        
                    

                    

                    

                
            
        
            
                
            
        

        
            
                
            
            
            
        

        
            
                
            
        

        
            
                
            
            
                
            
        

        
            
                
                    
                

                

                    

                

            
            
                
            

        

        
            
                
                    
                
            
        


        

        
            

                

                    
                        
                            
                        
                    

                    

                    

                
            
        

        
            

                

                    
                        
                            
                        
                    

                    

                    

                
            
        

        
            

                

                    
                        
                            
                        
                    

                    

                    

                
            
        


        
            

                

                    
                        
                            
                        
                    

                    

                    

                
            
        
        


        
        
            
            

            
            
                
            
            
                
            
        


        
            
            

            
            
            

            

            
        
            
            

            
            
                
            
            
                
            
        


        
            
            

            
            
            

            

            
        
        

        
        

            
            
            
                
            
        
    















    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageContent&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//div[@id='pageContent']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GJMissing'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AWorld QA Accounting Payroll'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//body/div</value>
   </webElementXpaths>
</WebElementEntity>
